// *** Your name: 
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.*;

public class CirclePainterWindow extends JFrame implements ActionListener { 
	
	private CirclePanel circlePanel;
	private CirclePanelListener circlePanelListener;
	private JTextField radiusTextField;
	
	public CirclePainterWindow() {
		circlePanel = new CirclePanel();
		circlePanelListener = new CirclePanelListener(circlePanel);
		
		JPanel mainPanel = new JPanel();
		mainPanel.setLayout(new BorderLayout());
		mainPanel.add(circlePanel, BorderLayout.CENTER);
		
		// Create a panel for the buttons, label, and text field
		// and then add it in the south position.
		// Remember to add this as an ActionListener for the
		// buttons and text field.
		JPanel buttonPanel=new JPanel();
		JButton rm_recent=new JButton("remove recent");
		JButton rm_all=new JButton("remove all");
		rm_all.addActionListener(this);
		rm_recent.addActionListener(this);
		JLabel radLabel=new JLabel("radius:");
		radiusTextField = new JTextField("", 20);
		radiusTextField.setSize(circlePanel.getWidth()/5, radiusTextField.getHeight());
		buttonPanel.add(rm_recent);
		buttonPanel.add(rm_all);
		buttonPanel.add(radLabel);
		buttonPanel.add(radiusTextField);
		radiusTextField.addActionListener(this);
		mainPanel.add(buttonPanel, BorderLayout.SOUTH);
		// The line "radiusTextField.selectAll();" will be helpful for completing your requirements. 
		// You can look up what it does. 
		// As for where it goes, think about which section of your code it would be most helpful in.
		JMenuBar menuBar = new JMenuBar();
		JMenu color=new JMenu("Color");
		JMenuItem red=new JMenuItem("Red");
		JMenuItem green=new JMenuItem("Green");
		JMenuItem blue=new JMenuItem("Blue");
		red.addActionListener(this);
		green.addActionListener(this);
		blue.addActionListener(this);
		menuBar.add(color);
		color.add(red);
		color.add(green);
		color.add(blue);
		//Create a Color menu for the menu bar with Red, Blue, and Green menu items.
		//Remember to add this as an ActionListener for the menu items.
		
		this.setContentPane(mainPanel);
		this.setJMenuBar(menuBar);

	}


	@Override
	public void actionPerformed(ActionEvent ev) {
		//write code to respond appropriately to all of the possible
		//ActionEvents generated by the menu items, buttons, and text field
		if(ev.getSource() instanceof JTextField){
			try{
				int input=Integer.parseInt(radiusTextField.getText());
				if(input<=0)
					throw new Exception();
				circlePanelListener.setRadiusOfNewlyCreatedCircles(input);
			}catch(Exception e){
				radiusTextField.setText("Must enter a positive integer.");
				radiusTextField.selectAll();
			}
			return;
		}
		switch (ev.getActionCommand()){
			case "remove recent"->circlePanel.removeMostRecentCircle();
			case "remove all"->circlePanel.removeAllCircles();
			case "Red"->circlePanelListener.setColorOfNewlyCreatedCircles(Color.RED);
			case "Green"->circlePanelListener.setColorOfNewlyCreatedCircles(Color.GREEN);
			case "Blue"->circlePanelListener.setColorOfNewlyCreatedCircles(Color.BLUE);
			default->System.err.println("Unexpected ActionCommand: "+ev.getActionCommand());
		}
	}
	

}
